export const locationData: Record<string, string[]> = {
  "Afghanistan": ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Jalalabad"],
  "Albania": ["Tirana", "Durres", "Vlore", "Elbasan", "Shkoder"],
  "Algeria": ["Algiers", "Oran", "Constantine", "Annaba", "Blida"],
  "Andorra": ["Andorra la Vella", "Escaldes-Engordany"],
  "Angola": ["Luanda", "Huambo", "Lobito", "Benguela", "Lubango"],
  "Antigua and Barbuda": ["St. John's"],
  "Argentina": ["Buenos Aires", "Cordoba", "Rosario", "Mendoza", "La Plata", "Tucuman", "Mar del Plata", "Salta", "Santa Fe", "San Juan"],
  "Armenia": ["Yerevan", "Gyumri", "Vanadzor"],
  "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Canberra", "Newcastle", "Hobart", "Darwin", "Cairns", "Townsville", "Geelong", "Wollongong"],
  "Austria": ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck", "Klagenfurt"],
  "Azerbaijan": ["Baku", "Ganja", "Sumqayit"],
  "Bahamas": ["Nassau", "Freeport"],
  "Bahrain": ["Manama", "Riffa", "Muharraq"],
  "Bangladesh": ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet", "Comilla"],
  "Barbados": ["Bridgetown"],
  "Belarus": ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno", "Brest"],
  "Belgium": ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liege", "Bruges", "Namur", "Leuven"],
  "Belize": ["Belize City", "Belmopan", "San Ignacio"],
  "Benin": ["Cotonou", "Porto-Novo", "Parakou"],
  "Bhutan": ["Thimphu", "Phuntsholing"],
  "Bolivia": ["La Paz", "Santa Cruz", "Cochabamba", "Sucre", "Oruro"],
  "Bosnia and Herzegovina": ["Sarajevo", "Banja Luka", "Tuzla", "Mostar", "Zenica"],
  "Botswana": ["Gaborone", "Francistown", "Maun"],
  "Brazil": ["Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Porto Alegre", "Goiania", "Belem", "Campinas", "Florianopolis", "Natal"],
  "Brunei": ["Bandar Seri Begawan"],
  "Bulgaria": ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse"],
  "Burkina Faso": ["Ouagadougou", "Bobo-Dioulasso"],
  "Burundi": ["Bujumbura", "Gitega"],
  "Cambodia": ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville"],
  "Cameroon": ["Douala", "Yaounde", "Bamenda", "Garoua"],
  "Canada": ["Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Quebec City", "Hamilton", "Halifax", "Victoria", "Saskatoon", "Regina", "St. John's", "Kelowna", "London", "Kitchener", "Windsor", "Barrie", "Oshawa"],
  "Cape Verde": ["Praia", "Mindelo"],
  "Central African Republic": ["Bangui"],
  "Chad": ["N'Djamena", "Moundou"],
  "Chile": ["Santiago", "Valparaiso", "Concepcion", "Antofagasta", "Temuco", "Vina del Mar", "La Serena", "Iquique"],
  "China": ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Chongqing", "Hangzhou", "Wuhan", "Nanjing", "Xi'an", "Tianjin", "Suzhou", "Dongguan", "Shenyang", "Qingdao", "Dalian", "Harbin", "Zhengzhou", "Kunming", "Changsha", "Xiamen", "Hefei", "Fuzhou", "Jinan"],
  "Colombia": ["Bogota", "Medellin", "Cali", "Barranquilla", "Cartagena", "Bucaramanga", "Cucuta", "Pereira"],
  "Comoros": ["Moroni"],
  "Congo": ["Brazzaville", "Pointe-Noire"],
  "Costa Rica": ["San Jose", "Limon", "Alajuela", "Heredia"],
  "Croatia": ["Zagreb", "Split", "Rijeka", "Osijek", "Dubrovnik", "Zadar"],
  "Cuba": ["Havana", "Santiago de Cuba", "Camaguey", "Holguin", "Santa Clara"],
  "Cyprus": ["Nicosia", "Limassol", "Larnaca", "Paphos", "Famagusta"],
  "Czech Republic": ["Prague", "Brno", "Ostrava", "Pilsen", "Liberec", "Olomouc"],
  "DR Congo": ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kananga", "Kisangani"],
  "Denmark": ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
  "Djibouti": ["Djibouti City"],
  "Dominica": ["Roseau"],
  "Dominican Republic": ["Santo Domingo", "Santiago", "San Pedro de Macoris", "La Romana"],
  "Ecuador": ["Quito", "Guayaquil", "Cuenca", "Ambato", "Manta"],
  "Egypt": ["Cairo", "Alexandria", "Giza", "Shubra El Kheima", "Port Said", "Suez", "Luxor", "Aswan", "Mansoura"],
  "El Salvador": ["San Salvador", "Santa Ana", "San Miguel"],
  "Equatorial Guinea": ["Malabo", "Bata"],
  "Eritrea": ["Asmara", "Keren"],
  "Estonia": ["Tallinn", "Tartu", "Narva", "Parnu"],
  "Eswatini": ["Mbabane", "Manzini"],
  "Ethiopia": ["Addis Ababa", "Dire Dawa", "Mekelle", "Gondar", "Hawassa", "Bahir Dar"],
  "Fiji": ["Suva", "Lautoka", "Nadi"],
  "Finland": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Jyvaskyla"],
  "France": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille", "Rennes", "Reims", "Toulon", "Le Havre", "Grenoble", "Dijon", "Angers"],
  "Gabon": ["Libreville", "Port-Gentil"],
  "Gambia": ["Banjul", "Serekunda"],
  "Georgia": ["Tbilisi", "Batumi", "Kutaisi", "Rustavi"],
  "Germany": ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Dusseldorf", "Leipzig", "Dortmund", "Essen", "Bremen", "Dresden", "Hanover", "Nuremberg", "Duisburg", "Bochum", "Wuppertal", "Bonn", "Munster", "Mannheim"],
  "Ghana": ["Accra", "Kumasi", "Tamale", "Sekondi-Takoradi", "Cape Coast"],
  "Greece": ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa", "Volos", "Ioannina", "Rhodes"],
  "Grenada": ["St. George's"],
  "Guatemala": ["Guatemala City", "Quetzaltenango", "Escuintla", "Mixco"],
  "Guinea": ["Conakry", "Nzerekore", "Kankan"],
  "Guinea-Bissau": ["Bissau"],
  "Guyana": ["Georgetown", "Linden"],
  "Haiti": ["Port-au-Prince", "Cap-Haitien", "Gonaives"],
  "Honduras": ["Tegucigalpa", "San Pedro Sula", "La Ceiba", "Choloma"],
  "Hungary": ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pecs", "Gyor"],
  "Iceland": ["Reykjavik", "Kopavogur", "Akureyri"],
  "India": ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata", "Pune", "Jaipur", "Surat", "Lucknow", "Kanpur", "Nagpur", "Indore", "Thane", "Bhopal", "Visakhapatnam", "Patna", "Vadodara", "Ghaziabad", "Ludhiana", "Agra", "Coimbatore", "Kochi", "Chandigarh"],
  "Indonesia": ["Jakarta", "Surabaya", "Bandung", "Medan", "Semarang", "Makassar", "Palembang", "Depok", "Tangerang", "Denpasar", "Yogyakarta", "Malang", "Balikpapan"],
  "Iran": ["Tehran", "Mashhad", "Isfahan", "Karaj", "Tabriz", "Shiraz", "Ahvaz", "Qom", "Kermanshah"],
  "Iraq": ["Baghdad", "Basra", "Erbil", "Mosul", "Sulaymaniyah", "Kirkuk", "Najaf", "Karbala"],
  "Ireland": ["Dublin", "Cork", "Galway", "Limerick", "Waterford", "Kilkenny", "Drogheda"],
  "Israel": ["Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva", "Ashdod", "Netanya", "Beer Sheva"],
  "Italy": ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Catania", "Bari", "Venice", "Verona", "Messina", "Padua", "Trieste", "Brescia", "Parma"],
  "Ivory Coast": ["Abidjan", "Bouake", "Yamoussoukro", "Daloa"],
  "Jamaica": ["Kingston", "Montego Bay", "Spanish Town", "Portmore"],
  "Japan": ["Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo", "Fukuoka", "Kobe", "Kyoto", "Kawasaki", "Saitama", "Hiroshima", "Sendai", "Kitakyushu", "Chiba", "Sakai", "Niigata", "Hamamatsu", "Shizuoka", "Okayama"],
  "Jordan": ["Amman", "Zarqa", "Irbid", "Aqaba"],
  "Kazakhstan": ["Almaty", "Astana", "Shymkent", "Karaganda", "Aktobe", "Atyrau"],
  "Kenya": ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Malindi"],
  "Kiribati": ["Tarawa"],
  "Kosovo": ["Pristina", "Prizren", "Peja", "Mitrovica"],
  "Kuwait": ["Kuwait City", "Hawalli", "Salmiya", "Jahra"],
  "Kyrgyzstan": ["Bishkek", "Osh", "Jalal-Abad"],
  "Laos": ["Vientiane", "Luang Prabang", "Savannakhet"],
  "Latvia": ["Riga", "Daugavpils", "Liepaja", "Jelgava"],
  "Lebanon": ["Beirut", "Tripoli", "Sidon", "Tyre", "Jounieh"],
  "Lesotho": ["Maseru"],
  "Liberia": ["Monrovia"],
  "Libya": ["Tripoli", "Benghazi", "Misrata"],
  "Liechtenstein": ["Vaduz", "Schaan"],
  "Lithuania": ["Vilnius", "Kaunas", "Klaipeda", "Siauliai", "Panevezys"],
  "Luxembourg": ["Luxembourg City", "Esch-sur-Alzette", "Differdange"],
  "Madagascar": ["Antananarivo", "Toamasina", "Antsirabe"],
  "Malawi": ["Lilongwe", "Blantyre", "Mzuzu"],
  "Malaysia": ["Kuala Lumpur", "George Town", "Johor Bahru", "Ipoh", "Shah Alam", "Kota Kinabalu", "Kuching", "Petaling Jaya", "Melaka"],
  "Maldives": ["Male"],
  "Mali": ["Bamako", "Sikasso", "Mopti"],
  "Malta": ["Valletta", "Birkirkara", "Sliema"],
  "Marshall Islands": ["Majuro"],
  "Mauritania": ["Nouakchott", "Nouadhibou"],
  "Mauritius": ["Port Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe"],
  "Mexico": ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "Leon", "Ciudad Juarez", "Zapopan", "Merida", "Cancun", "Queretaro", "Aguascalientes", "San Luis Potosi", "Chihuahua", "Morelia", "Saltillo", "Veracruz", "Oaxaca", "Playa del Carmen"],
  "Micronesia": ["Palikir"],
  "Moldova": ["Chisinau", "Balti", "Tiraspol"],
  "Monaco": ["Monaco"],
  "Mongolia": ["Ulaanbaatar", "Erdenet", "Darkhan"],
  "Montenegro": ["Podgorica", "Niksic", "Budva", "Bar", "Kotor"],
  "Morocco": ["Casablanca", "Rabat", "Fez", "Marrakech", "Tangier", "Agadir", "Meknes", "Oujda", "Kenitra"],
  "Mozambique": ["Maputo", "Matola", "Beira", "Nampula"],
  "Myanmar": ["Yangon", "Mandalay", "Naypyidaw", "Mawlamyine"],
  "Namibia": ["Windhoek", "Walvis Bay", "Swakopmund"],
  "Nauru": ["Yaren"],
  "Nepal": ["Kathmandu", "Pokhara", "Lalitpur", "Biratnagar", "Bharatpur"],
  "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Tilburg", "Groningen", "Almere", "Breda", "Nijmegen", "Maastricht", "Haarlem"],
  "New Zealand": ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Dunedin", "Palmerston North", "Napier", "Nelson", "Queenstown"],
  "Nicaragua": ["Managua", "Leon", "Masaya", "Granada"],
  "Niger": ["Niamey", "Zinder", "Maradi"],
  "Nigeria": ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt", "Benin City", "Kaduna", "Maiduguri", "Enugu", "Calabar", "Jos", "Ilorin", "Owerri", "Abeokuta", "Warri"],
  "North Korea": ["Pyongyang", "Hamhung", "Chongjin"],
  "North Macedonia": ["Skopje", "Bitola", "Kumanovo", "Ohrid"],
  "Norway": ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen", "Fredrikstad", "Tromso", "Kristiansand"],
  "Oman": ["Muscat", "Salalah", "Sohar", "Sur"],
  "Pakistan": ["Karachi", "Lahore", "Islamabad", "Faisalabad", "Rawalpindi", "Multan", "Peshawar", "Quetta", "Hyderabad", "Sialkot", "Gujranwala"],
  "Palau": ["Ngerulmud"],
  "Palestine": ["Gaza", "Ramallah", "Hebron", "Nablus", "Bethlehem", "Jenin"],
  "Panama": ["Panama City", "Colon", "David"],
  "Papua New Guinea": ["Port Moresby", "Lae", "Mount Hagen"],
  "Paraguay": ["Asuncion", "Ciudad del Este", "San Lorenzo", "Encarnacion"],
  "Peru": ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Cusco", "Iquitos", "Piura", "Huancayo"],
  "Philippines": ["Manila", "Quezon City", "Davao", "Cebu City", "Zamboanga", "Antipolo", "Pasig", "Taguig", "Cagayan de Oro", "Makati", "Caloocan", "Bacolod", "Iloilo City"],
  "Poland": ["Warsaw", "Krakow", "Lodz", "Wroclaw", "Poznan", "Gdansk", "Szczecin", "Lublin", "Katowice", "Bydgoszcz", "Bialystok", "Torun"],
  "Portugal": ["Lisbon", "Porto", "Braga", "Coimbra", "Funchal", "Amadora", "Setubal", "Faro", "Aveiro"],
  "Qatar": ["Doha", "Al Wakrah", "Al Rayyan", "Al Khor"],
  "Romania": ["Bucharest", "Cluj-Napoca", "Timisoara", "Iasi", "Constanta", "Craiova", "Brasov", "Galati", "Sibiu", "Oradea"],
  "Russia": ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Nizhny Novgorod", "Chelyabinsk", "Samara", "Omsk", "Rostov-on-Don", "Ufa", "Krasnoyarsk", "Voronezh", "Perm", "Volgograd", "Krasnodar", "Sochi"],
  "Rwanda": ["Kigali", "Butare", "Gisenyi"],
  "Saint Kitts and Nevis": ["Basseterre"],
  "Saint Lucia": ["Castries"],
  "Saint Vincent and the Grenadines": ["Kingstown"],
  "Samoa": ["Apia"],
  "San Marino": ["San Marino"],
  "Sao Tome and Principe": ["Sao Tome"],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar", "Dhahran", "Tabuk", "Buraydah", "Abha"],
  "Senegal": ["Dakar", "Thies", "Saint-Louis", "Kaolack"],
  "Serbia": ["Belgrade", "Novi Sad", "Nis", "Kragujevac", "Subotica"],
  "Seychelles": ["Victoria"],
  "Sierra Leone": ["Freetown", "Bo", "Kenema"],
  "Singapore": ["Singapore"],
  "Slovakia": ["Bratislava", "Kosice", "Zilina", "Nitra", "Presov", "Banska Bystrica"],
  "Slovenia": ["Ljubljana", "Maribor", "Celje", "Kranj"],
  "Solomon Islands": ["Honiara"],
  "Somalia": ["Mogadishu", "Hargeisa", "Kismayo"],
  "South Africa": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein", "East London", "Pietermaritzburg", "Nelspruit", "Polokwane", "Kimberley", "Stellenbosch"],
  "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon", "Ulsan", "Changwon", "Seongnam", "Goyang", "Yongin", "Jeju"],
  "South Sudan": ["Juba", "Malakal", "Wau"],
  "Spain": ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Malaga", "Murcia", "Palma", "Las Palmas", "Bilbao", "Alicante", "Cordoba", "Valladolid", "Vigo", "Gijon", "Granada", "San Sebastian", "Salamanca", "Marbella"],
  "Sri Lanka": ["Colombo", "Kandy", "Galle", "Jaffna", "Negombo", "Trincomalee"],
  "Sudan": ["Khartoum", "Omdurman", "Port Sudan", "Kassala"],
  "Suriname": ["Paramaribo"],
  "Sweden": ["Stockholm", "Gothenburg", "Malmo", "Uppsala", "Vasteras", "Orebro", "Linkoping", "Helsingborg", "Jonkoping", "Norrkoping", "Lund", "Umea"],
  "Switzerland": ["Zurich", "Geneva", "Basel", "Bern", "Lausanne", "Winterthur", "Lucerne", "St. Gallen", "Lugano", "Biel"],
  "Syria": ["Damascus", "Aleppo", "Homs", "Latakia", "Hama"],
  "Taiwan": ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Hsinchu", "Keelung", "Taoyuan"],
  "Tajikistan": ["Dushanbe", "Khujand"],
  "Tanzania": ["Dar es Salaam", "Dodoma", "Mwanza", "Arusha", "Zanzibar City", "Mbeya"],
  "Thailand": ["Bangkok", "Chiang Mai", "Pattaya", "Nonthaburi", "Hat Yai", "Nakhon Ratchasima", "Udon Thani", "Phuket", "Khon Kaen", "Chiang Rai"],
  "Timor-Leste": ["Dili", "Baucau"],
  "Togo": ["Lome", "Sokode"],
  "Tonga": ["Nukualofa"],
  "Trinidad and Tobago": ["Port of Spain", "San Fernando", "Chaguanas"],
  "Tunisia": ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte"],
  "Turkey": ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana", "Gaziantep", "Konya", "Mersin", "Kayseri", "Diyarbakir", "Eskisehir", "Trabzon", "Samsun"],
  "Turkmenistan": ["Ashgabat", "Turkmenabat", "Dashoguz"],
  "Tuvalu": ["Funafuti"],
  "Uganda": ["Kampala", "Gulu", "Mbarara", "Jinja", "Entebbe"],
  "UK": ["London", "Birmingham", "Manchester", "Leeds", "Glasgow", "Liverpool", "Newcastle", "Sheffield", "Bristol", "Edinburgh", "Leicester", "Coventry", "Nottingham", "Belfast", "Cardiff", "Brighton", "Southampton", "Oxford", "Cambridge", "Aberdeen", "York", "Bath", "Exeter", "Canterbury", "Swansea", "Dundee", "Reading", "Plymouth"],
  "Ukraine": ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Lviv", "Donetsk", "Zaporizhzhia", "Mykolaiv", "Mariupol", "Vinnytsia"],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Al Ain", "Ras Al Khaimah", "Fujairah"],
  "Uruguay": ["Montevideo", "Salto", "Paysandu", "Las Piedras"],
  "USA": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus", "Charlotte", "Indianapolis", "San Francisco", "Seattle", "Denver", "Washington DC", "Nashville", "Oklahoma City", "El Paso", "Boston", "Portland", "Las Vegas", "Memphis", "Louisville", "Baltimore", "Milwaukee", "Albuquerque", "Tucson", "Fresno", "Sacramento", "Mesa", "Kansas City", "Atlanta", "Omaha", "Colorado Springs", "Raleigh", "Long Beach", "Virginia Beach", "Miami", "Oakland", "Minneapolis", "Tampa", "Tulsa", "Arlington", "New Orleans", "Orlando", "St. Louis", "Pittsburgh", "Cincinnati", "Honolulu", "Anchorage", "Detroit", "Salt Lake City", "Boise", "Richmond"],
  "Uzbekistan": ["Tashkent", "Samarkand", "Bukhara", "Namangan", "Fergana", "Andijan"],
  "Vanuatu": ["Port Vila"],
  "Vatican City": ["Vatican City"],
  "Venezuela": ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay", "Ciudad Guayana"],
  "Vietnam": ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hai Phong", "Can Tho", "Nha Trang", "Hue", "Bien Hoa", "Vung Tau"],
  "Yemen": ["Sanaa", "Aden", "Taiz", "Hodeidah"],
  "Zambia": ["Lusaka", "Ndola", "Kitwe", "Livingstone"],
  "Zimbabwe": ["Harare", "Bulawayo", "Mutare", "Gweru", "Masvingo"],
};

export const allCountries = Object.keys(locationData).sort();

export function getCitiesForCountry(country: string): string[] {
  return locationData[country] || [];
}
